language: ruby
rvm:
- 2.2.0
install:
- bundle install --path vendor/bundle
script: bundle exec rspec
env:
  secure: tDtn4IcvLaWvD5NFXizCXsLuvGhcAxk0Kf/ix4Y/3tryAKKrCZPLMyxV2NGG6iZKdIxl5rhD539XgWAvPn52ue3hh0J/DenTpHSAWt9V/N9hMghYmyEL2bdyMSR9l2mZkRfwTNcbOmAuwtVUQyVi2eqyzlBwHSLZR3Be11xN6gxVMxpzWuFjynmomQxiTxGZVL0L4idSCRqrLIRZncCHzb+6EBeIjz9TuR7sJoVl9VmpyIqWWHDqbgUWAQJE1j4btcqbMOQ0F6RX/LnboGuzFyqUI3/shnTuo+T4bSFPn3vfS4RWGgoMOYwb1vECDG9YrpwFA7O7KwSZeezLslAcGry918kXuXN73SQ6NiwRQVAN9qkfVe4Y9qnOcVrcNCw3lycsio0OJdWd/LaZN5p0uzl7bPke0XR69HauA0BNC9+Cx6HKp7HnECjcqJKCv7n2Epqfl9Zp7op2ep5nPBLx4msGEodterNNnWp2cy7Wu7/aks87Dt60jhc8QsDDkYYdpUvg17Ei3nt9unrHLmwh1yOR65OQcLlCLwmjc+lPE4iAO+UIdjZdGQRMNznF/5V8XNumftxlhhuay4bFYiMR7CiRnhHOuu9JtfRpYG/x69xfOD0RP81vrtS6GIloXV1KslRGu+26iOhS9bZoUHpQeo53yAHLwUEO82T8z50UC68=
